---

Description: Define "build user", which is an identity used by build tools (e.g. Travis, Jenkins) to interact with resources in this environment.
AWSTemplateFormatVersion: 2010-09-09

Parameters:

  AccessKeySerial:
    Type: Number
    Default: 0

Resources:

  BuildUser:
    Type: "AWS::IAM::User"
    Properties:
#      Path: /bookit/builds/
      Policies:
        - PolicyName: Ecr
          PolicyDocument:
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "ecr:CreateRepository",
                            "ecr:GetAuthorizationToken",
                            "ecr:BatchCheckLayerAvailability",
                            "ecr:GetDownloadUrlForLayer",
                            "ecr:GetRepositoryPolicy",
                            "ecr:DescribeRepositories",
                            "ecr:ListImages",
                            "ecr:DescribeImages",
                            "ecr:BatchGetImage",
                            "ecr:InitiateLayerUpload",
                            "ecr:UploadLayerPart",
                            "ecr:CompleteLayerUpload",
                            "ecr:PutImage"
                        ],
                        "Resource": "*"
                    }
                ]
            }
        - PolicyName: Ecs
          PolicyDocument:
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "ecs:*",
                            "iam:PassRole"
                        ],
                        "Resource": "*"
                    }
                ]
            }
        - PolicyName: S3
          PolicyDocument:
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "s3:Get*",
                            "s3:List*"
                        ],
                        "Resource": "arn:aws:s3:::rig.*"
                    }
                ]
            }
        - PolicyName: Ssm
          PolicyDocument:
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "ssm:GetParameters"
                        ],
                        "Resource": "arn:aws:ssm:us-east-1:*"
                    }
                ]
            }

  BuildAccessKey:
    Type: "AWS::IAM::AccessKey"
    Properties:
      Serial: !Ref AccessKeySerial
      UserName: !Ref BuildUser

Outputs:
  BuildUserName:
    Description: Name of build user.
    Value: !Ref BuildUser

  BuildUserArn:
    Description: ARN for build user.
    Value: !GetAtt BuildUser.Arn

  BuildUserAccessKey:
    Description: API access key for build user.
    Value: !Ref BuildAccessKey

  BuildUserAccessSecretKey:
    Description: API access secret key for build user.
    Value: !GetAtt BuildAccessKey.SecretAccessKey

